spring.application.name=EncurtaUrl

# Configura��o do DataSource para MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/DbEncurtaUrl
spring.datasource.username=root
spring.datasource.password=Marioviado1@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

logging.level.com.yourpackage=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE